# v8_worked_example_fixed.py
# Fix: DO NOT use old-style "%" formatting when generating TeX (TeX uses % heavily).

import argparse
import os
import json
import numpy as np

def _load_npz(path: str):
    if not os.path.exists(path):
        raise FileNotFoundError(f"NPZ not found: {path}")
    return np.load(path, allow_pickle=True)

def _pick_key(d, candidates):
    for k in candidates:
        if k in d.files:
            return k
    return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exp", required=True, help="experiment id (hex)")
    ap.add_argument("--in-dir", default="nnbd_v8_out", help="directory containing coupling_*.npz")
    ap.add_argument("--out-dir", default=".", help="where to write worked_example_<exp>.tex")
    ap.add_argument("--idx", type=int, default=None, help="grid index (default: middle)")
    args = ap.parse_args()

    npz_path = os.path.join(args.in_dir, f"coupling_{args.exp}.npz")
    z = _load_npz(npz_path)

    # Try common key names (robust to slight pipeline changes)
    kT = _pick_key(z, ["T", "Ts", "grid_T"])
    kEg = _pick_key(z, ["E_gamma", "Egamma", "Eg"])
    kEp = _pick_key(z, ["E_prime", "Eprime", "Ep"])
    kD  = _pick_key(z, ["D", "D_theta", "Dtheta"])
    kQ  = _pick_key(z, ["Q", "Q_theta", "Qtheta"])

    if kT is None or kEg is None or kEp is None:
        raise KeyError(f"Missing required keys in NPZ. Have keys: {z.files}")

    T = np.array(z[kT], dtype=float)
    Eg = z[kEg]
    Ep = z[kEp]

    # Eg/Ep might be complex arrays, or stored as (real, imag). Handle both.
    Eg = np.array(Eg)
    Ep = np.array(Ep)

    if np.iscomplexobj(Eg):
        Egc = Eg.astype(np.complex128)
    else:
        # try split
        if Eg.ndim == 2 and Eg.shape[1] == 2:
            Egc = Eg[:,0] + 1j*Eg[:,1]
        else:
            raise ValueError("E_gamma not complex and not (N,2) real/imag.")

    if np.iscomplexobj(Ep):
        Epc = Ep.astype(np.complex128)
    else:
        if Ep.ndim == 2 and Ep.shape[1] == 2:
            Epc = Ep[:,0] + 1j*Ep[:,1]
        else:
            raise ValueError("E_prime not complex and not (N,2) real/imag.")

    N = len(T)
    idx = args.idx if args.idx is not None else (N // 2)
    if not (0 <= idx < N):
        raise IndexError(f"idx out of range: idx={idx}, N={N}")

    # If D/Q exist, use them; else compute D as Re(Eg-Ep) and Q via sample var.
    if kD is not None:
        D = np.array(z[kD], dtype=float)
    else:
        D = np.real(Egc - Epc)

    var = float(np.var(D, ddof=1)) if N >= 2 else float(np.var(D))
    Q = (D / np.sqrt(var)) if var > 0 else np.full_like(D, np.nan)

    Ti = float(T[idx])
    Eg_i = Egc[idx]
    Ep_i = Epc[idx]
    D_i = float(D[idx])
    Q_i = float(Q[idx])

    out_name = f"worked_example_{args.exp}.tex"
    out_path = os.path.join(args.out_dir, out_name)

    # IMPORTANT: f-string / format only. No "%" formatting anywhere.
    tex = (
        "% Auto-generated by v8_worked_example_fixed.py\n"
        f"\\subsection*{{Worked example (exp={args.exp})}}\n"
        f"Grid size $N={N}$, chosen index $j={idx}$, $T={Ti:.6f}$. \n\n"
        "\\begin{align*}\n"
        f"E_\\gamma(T) &= {Eg_i.real:.12f} + i({Eg_i.imag:.12f}),\\\\\n"
        f"E_p(T) &= {Ep_i.real:.12f} + i({Ep_i.imag:.12f}),\\\\\n"
        f"D_\\theta(T) &= \\Re(E_\\gamma(T)-E_p(T)) = {D_i:.12f},\\\\\n"
        f"\\widehat{{\\mathrm{{Var}}}}(D_\\theta) &= {var:.12f},\\\\\n"
        f"Q_\\theta(T) &= \\frac{{D_\\theta(T)}}{{\\sqrt{{\\widehat{{\\mathrm{{Var}}}}(D_\\theta)}}}} = {Q_i:.12f}.\n"
        "\\end{align*}\n"
    )

    os.makedirs(args.out_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(tex)

    print(f"[OK] wrote {out_path}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())